const months=[
{name:"Enero",text:"Arrancamos sin mapa, con la sensación de que todo recién empezaba.",card:"#07553b",card2:"#ef3e32",card3:"#f3c942",detail:"#ff6048",bg:"#e8f0d5",x:-8,y:-4,r:-3},{name:"Febrero",text:"Lluvia en los vidrios y una conversación que se nos hizo de noche.",card:"#d52632",card2:"#124d35",card3:"#ff7051",detail:"#143c2c",bg:"#f5c9c0",x:10,y:4,r:4},{name:"Marzo",text:"Una manta sobre el pasto y nada urgente por hacer.",card:"#397b39",card2:"#ed3f2f",card3:"#b5d64d",detail:"#f04e3e",bg:"#dcebbd",x:-12,y:8,r:-5},{name:"Abril",text:"Las bicis quedaron entre flores. Nosotros seguimos caminando.",card:"#f04a32",card2:"#0c684b",card3:"#f7bc3d",detail:"#0f513a",bg:"#f4d5be",x:7,y:-7,r:2},{name:"Mayo",text:"El lago se quedó con todo el cielo y nosotros con la tarde.",card:"#0b5942",card2:"#e63339",card3:"#72a943",detail:"#ff5c42",bg:"#c6e0c5",x:-5,y:3,r:5},{name:"Junio",text:"Ventanillas bajas, una canción repetida y kilómetros por delante.",card:"#c91f2c",card2:"#15583e",card3:"#e9cf53",detail:"#10402f",bg:"#f0c9b4",x:12,y:-2,r:-4},{name:"Julio",text:"El mar helado, la arena en todas partes y el mejor atardecer.",card:"#f0442f",card2:"#064f38",card3:"#ffbf35",detail:"#0f684b",bg:"#f2b9a5",x:-9,y:-6,r:3},{name:"Agosto",text:"Luces de feria. Perdimos una apuesta y ganamos una historia.",card:"#174c35",card2:"#df2935",card3:"#ff713f",detail:"#e72c38",bg:"#c9dfb9",x:6,y:7,r:-2},{name:"Septiembre",text:"Desde arriba, hasta los problemas parecían pequeños.",card:"#2f7d45",card2:"#e93535",card3:"#d7de52",detail:"#f04d38",bg:"#d5e8bd",x:-11,y:2,r:4},{name:"Octubre",text:"Hojas secas, una casa de madera y la primera noche de frío.",card:"#bd252d",card2:"#104b36",card3:"#f28534",detail:"#0a6445",bg:"#e9c49d",x:9,y:-5,r:-5},{name:"Noviembre",text:"Una mesa larga, platos compartidos y nadie mirando la hora.",card:"#ef4335",card2:"#14543b",card3:"#f6bc38",detail:"#063e2d",bg:"#f2c7b8",x:-6,y:6,r:2},{name:"Diciembre",text:"Afuera caía la noche; adentro estábamos todos.",card:"#095039",card2:"#d72432",card3:"#8dbb47",detail:"#f04b38",bg:"#cbdcb9",x:4,y:-3,r:-3}];
const DEPTH=1250,world=document.querySelector("#world"),story=document.querySelector("#story"),intro=document.querySelector("#intro"),enterButton=document.querySelector("#enterButton"),motionToggle=document.querySelector("#motionToggle"),number=document.querySelector("#monthNumber"),monthName=document.querySelector("#monthName"),monthText=document.querySelector("#monthText"),progressBar=document.querySelector("#progressBar");let paused=false,ticking=false;
months.forEach((month,index)=>{world.insertAdjacentHTML("beforeend",`<article class="memory-frame" data-index="${index}" style="--z:${index*-DEPTH}px;--x:${month.x}vw;--y:${month.y}vh;--r:${month.r}deg;--card:${month.card};--card2:${month.card2};--card3:${month.card3};--detail:${month.detail}"><div class="color-card photo-main" data-month="${month.name}"><i class="orb"></i></div><div class="color-card photo-two" aria-label="Segunda foto de ${month.name}"></div><div class="color-card photo-three" aria-label="Tercera foto de ${month.name}"></div><span class="frame-number">3 FOTOS · ${String(index+1).padStart(2,"0")}</span></article>`);story.insertAdjacentHTML("beforeend",`<section class="story-step" aria-label="${month.name}: ${month.text}"></section>`)});
const frames=[...document.querySelectorAll(".memory-frame")];
function updateCaption(index){const month=months[index];if(monthName.textContent===month.name)return;number.textContent=String(index+1).padStart(2,"0");monthName.textContent=month.name;monthText.textContent=month.text;document.body.style.setProperty("--active-bg",month.bg);document.title=`${month.name} — Nuestro año`}
function render(){const max=document.documentElement.scrollHeight-window.innerHeight,raw=max>0?window.scrollY/max:0,journey=raw*(months.length-1),cameraZ=journey*DEPTH,active=Math.max(0,Math.min(months.length-1,Math.round(journey))),sway=paused?0:Math.sin(raw*Math.PI*5)*1.2;world.style.transform=`translate3d(0,0,${cameraZ}px) rotateZ(${sway}deg)`;frames.forEach((frame,index)=>{const distance=Math.abs(index-journey);frame.style.opacity=String(Math.max(0,Math.min(1,1.35-distance*.34)))});progressBar.style.height=`${raw*100}%`;updateCaption(active);ticking=false}
function requestRender(){if(!ticking){ticking=true;requestAnimationFrame(render)}}
enterButton.addEventListener("click",()=>{intro.classList.add("leaving");document.body.classList.remove("locked");window.scrollTo(0,0);requestRender()});
document.querySelector(".monogram").addEventListener("click",event=>{event.preventDefault();document.body.classList.add("locked");intro.classList.remove("leaving");window.scrollTo(0,0)});
motionToggle.addEventListener("click",()=>{paused=!paused;motionToggle.setAttribute("aria-pressed",String(paused));motionToggle.textContent=paused?"Activar movimiento":"Pausar movimiento";requestRender()});
window.addEventListener("scroll",requestRender,{passive:true});window.addEventListener("resize",requestRender);monthText.textContent=months[0].text;render();
